import json
from pydantic import BaseModel, Field, ValidationError
from ai_client import get_fireworks_client, FIREWORKS_CLASSIFIER_MODEL

# Pydantic model for schema validation
class ClassificationSchema(BaseModel):
    domain: str = Field(description="The domain of the document (e.g., Legal, Medical, Engineering)")
    doc_type: str = Field(description="The specific type of document (e.g., Master Service Agreement, Safety Manual)")
    suggested_schema: list[str] = Field(description="A list of 5 key attributes to extract from this type of document")

async def detect_document_context(text: str) -> dict:
    """
    Sends a snapshot of the document to Fireworks.ai to classify intent and suggest a schema.
    Uses Llama-3.1-8B.
    """
    # Snapshot: rough approximation of 1000 tokens (around 4000 characters)
    snapshot = text[:4000]
    
    prompt = f"""
    You are an expert document analyzer. Analyze the following document snippet and determine its domain, document type, and suggest a list of 5 key attributes (schema) to extract.
    Return ONLY a valid JSON object matching this exact schema:
    {{
        "domain": "string",
        "doc_type": "string",
        "suggested_schema": ["attr1", "attr2", "attr3", "attr4", "attr5"]
    }}
    
    Document Snippet:
    {snapshot}
    """
    
    client = get_fireworks_client()

    response = await client.chat.completions.create(
        model=FIREWORKS_CLASSIFIER_MODEL,
        messages=[{"role": "user", "content": prompt}],
        response_format={"type": "json_object"},
        temperature=0.0
    )
    
    raw_content = response.choices[0].message.content
    if not raw_content:
        raise ValueError("Empty response from AI client.")
        
    # Strip <think> blocks generated by reasoning models
    if "<think>" in raw_content and "</think>" in raw_content:
        raw_content = raw_content.split("</think>")[-1].strip()
        
    # Extract JSON between curly braces
    start_idx = raw_content.find('{')
    end_idx = raw_content.rfind('}') + 1
    if start_idx != -1 and end_idx != 0:
        raw_content = raw_content[start_idx:end_idx]
        
    try:
        parsed_json = json.loads(raw_content)
        # Validate against Pydantic model. Will raise ValidationError if it fails.
        validated = ClassificationSchema(**parsed_json)
        return validated.model_dump()
    except json.JSONDecodeError as e:
        raise ValueError(f"Failed to decode JSON from AI response: {str(e)}\nRaw Response: {raw_content}") from e
    except ValidationError as e:
        # Re-raise to ensure fail-fast behavior is caught by the API exception handler
        raise e
