import json
import asyncio
from pydantic import BaseModel, Field, ValidationError
from ai_client import get_fireworks_client, FIREWORKS_EXTRACTOR_MODEL

class KnowledgeTriple(BaseModel):
    subject: str = Field(description="The normalized entity name (e.g., 'ASEEM_NEUPANE')")
    predicate: str = Field(description="The relationship between subject and object")
    object: str = Field(description="The normalized entity name or value (e.g., 'SOFTWARE_ENGINEER')")
    context_source: str = Field(description="Short phrase from text justifying this triple")

class ExtractedTriples(BaseModel):
    triples: list[KnowledgeTriple]

class ZeroShotExtractor:
    def __init__(self):
        self.client = get_fireworks_client()

    async def extract_triples(self, text_chunk: str, suggested_schema: list) -> list[dict]:
        """
        Performs extraction of knowledge triples from a chunk of text based on the suggested schema.
        Enforces 'slug' strategy for entity names.
        """
        schema_str = ", ".join(suggested_schema)
        prompt = f"""
        Extract knowledge triples from the text below, focusing particularly on information related to these key attributes: {schema_str}.
        
        CRITICAL RULE - ENTITY RESOLUTION (SLUG STRATEGY):
        For the 'subject' and 'object' fields, you MUST normalize the entity name into a unique ID "slug" (uppercase, words separated by underscores). 
        For example: "Aseem" or "Aseem Neupane" must both be normalized to "ASEEM_NEUPANE".
        
        Return ONLY a JSON object with a list of triples matching this exact structure:
        {{
            "triples": [
                {{"subject": "ENTITY_SLUG", "predicate": "RELATIONSHIP_SLUG", "object": "ENTITY_SLUG_OR_VALUE", "context_source": "short phrase"}}
            ]
        }}
        
        Text:
        {text_chunk}
        """
        
        response = await self.client.chat.completions.create(
            model=FIREWORKS_EXTRACTOR_MODEL,
            messages=[{"role": "user", "content": prompt}],
            response_format={"type": "json_object"},
            temperature=0.0
        )
        
        raw_content = response.choices[0].message.content
        if not raw_content:
            return []
            
        # Strip <think> blocks generated by reasoning models
        if "<think>" in raw_content and "</think>" in raw_content:
            raw_content = raw_content.split("</think>")[-1].strip()
            
        # Extract JSON between curly braces
        start_idx = raw_content.find('{')
        end_idx = raw_content.rfind('}') + 1
        if start_idx != -1 and end_idx != 0:
            raw_content = raw_content[start_idx:end_idx]
            
        try:
            parsed_json = json.loads(raw_content)
            
            # Robustness: un-nest if the LLM wrapped it in a dummy key (e.g., {"a": {"triples": [...]}})
            if "triples" not in parsed_json:
                for value in parsed_json.values():
                    if isinstance(value, dict) and "triples" in value:
                        parsed_json = value
                        break
                    elif isinstance(value, list):
                        parsed_json = {"triples": value}
                        break

            validated = ExtractedTriples(**parsed_json)
            return [triple.model_dump() for triple in validated.triples]
        except (json.JSONDecodeError, ValidationError) as e:
            # Re-raise to enforce fail-fast behavior
            raise ValueError(f"Failed to validate LLM output in extractor: {str(e)}\nRaw: {raw_content}") from e

    async def sliding_window_extract(self, full_text: str, suggested_schema: list, window_size: int = 2000, overlap: int = 200) -> list[dict]:
        """
        Process the document in sliding windows asynchronously.
        """
        tasks = []
        start = 0
        text_length = len(full_text)
        
        while start < text_length:
            end = min(start + window_size, text_length)
            chunk = full_text[start:end]
            
            # Create async task for this chunk
            tasks.append(self.extract_triples(chunk, suggested_schema))
            
            if end == text_length:
                break
            
            start += (window_size - overlap)
            
        # Execute all window extractions concurrently
        results = await asyncio.gather(*tasks)
        
        # Flatten the list of lists
        all_triples = []
        for chunk_triples in results:
            all_triples.extend(chunk_triples)
            
        return all_triples
